pipeline {
    agent any
    environment {
        HAB_LICENSE="accept"
    }
    stages {
        stage('checkout') {
            checkout([
                $class: 'GitSCM',
                branches: [[name: 'refs/heads/master']],
                doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'CalibrationResults']],
                submoduleCfg: [],
                userRemoteConfigs: [[url: 'https://github.com/yonkornilov/golang-habitat-hello-world']]
            ])
        }
        stage('build') {
            steps {
                sh "Hello world"
            }
        }
    }
}