version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: <command>
  package:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - package
