Vagrant.configure("2") do |config|
  config.vm.define "nomad" do |subconfig|
    subconfig.vm.box = "bento/ubuntu-16.04"
    subconfig.vm.hostname = "nomad"
    subconfig.vm.network "private_network", ip: "192.168.50.2"
    subconfig.vm.network "forwarded_port", guest: 4646, host: 8080
    subconfig.vm.provision "shell", path: "scripts/install_nomad.sh"
  end

  config.vm.define "jenkins" do |subconfig|
    subconfig.vm.box = "bento/ubuntu-16.04"
    subconfig.vm.hostname = "jenkins-agent"
    subconfig.vm.network "private_network", ip: "192.168.50.3"
    subconfig.vm.network "forwarded_port", guest: 8080, host: 80
    subconfig.vm.synced_folder "synced/jenkins", "/srv/"
    subconfig.vm.provision "shell", path: "scripts/install_jenkins_agent.sh"
  end
end